
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka,http://peer2:7002/eureka
  instance:
    instance-id: deptclient8002
    prefer-ip-address: true
spring:
  application:
    name: dept